### PR TITLE
Add Service Catalog Provisioning support

### PR DESCRIPTION
**Pull request by agrare**
Add a ProvisionWorkflow subclass and `supports :catalog` to allow IBM CIC providers to provision VMs via Service Catalog

Depends on:
- [x] https://github.com/ManageIQ/manageiq-providers-openstack/pull/840

Fixes https://github.com/ManageIQ/manageiq-providers-ibm_cic/issues/28

### CODE REVIEW

**Comment by agrare** [comment]
@miq-bot cross-repo-tests https://github.com/ManageIQ/manageiq-providers-openstack/pull/840

**Comment by agrare** [comment]
Okay cross-repo is green

**Comment by agrare** [comment]
cc @Fryguy

**Comment by Fryguy** [comment]
Backported to `petrosian` in commit 79105b09a354cd8c2c0eb1cc94a61667f97827a3.

```text
commit 79105b09a354cd8c2c0eb1cc94a61667f97827a3
Author: Jason Frey <fryguy9@gmail.com>
Date:   Thu Mar 9 11:05:50 2023 -0500

    Merge pull request #31 from agrare/add_catalog_support_ibm_cic
    
    Add Service Catalog Provisioning support
    
    (cherry picked from commit fcce82c762ebaabf9bcb1764667c6d10e42e9af8)
```

**Pull request merged**
