### PR TITLE
add missing icon and update w/ ibm z logo

### PR DESCRIPTION
**Pull request by dongcc**
add missing icic vm logo and update w/ ibm z logo

### CODE REVIEW

**Comment by agrare** [comment]
Hey @dongcc I see we have an ibm_z_vm logo in the manageiq-decorators repo already https://github.com/ManageIQ/manageiq-decorators/pull/66/files

Are you seeing missing icons on the UI?

**Comment by dongcc** [comment]
> Hey @dongcc I see we have an ibm_z_vm logo in the manageiq-decorators repo already https://github.com/ManageIQ/manageiq-decorators/pull/66/files
> 
> Are you seeing missing icons on the UI?

it was reported by Kavya in the slack:

image

**Comment by agrare** [comment]
New logo looks good @dongcc can you amend your original commit rather than adding the ibm_z_vm logo in the first commit and removing it in the second as this add+remove will live in the history

**Review by agrare — APPROVED** [review]

**Comment by Fryguy** [comment]
This logo says `IBM Z`, but it's for IBM CIC.  Is that expected?

**Comment by agrare** [comment]
> This logo says IBM Z, but it's for IBM CIC. Is that expected?

@dongcc ^ ?

The old logo just said `IBM` so it never said `IBM CIC`

**Comment by dongcc** [comment]
> Also can you show before/after screenshots with this change in place?

this is the logo where it will be displayed, the cloud provider,  
image

I checked other cloud providers,  they are using the offering logo,  thus I think it might be better to use the cic logo. 
The reason why I used IBM Z logo as previously it's IBM logo.

**Comment by chessbyte** [comment]
@Fryguy unrelated to this PR, but it did make me question why we still have the quadicon, especially next to a summary of all the items we discovered during inventory refresh.

**Comment by Fryguy** [comment]
@chessbyte I agree.  They are still used in a handful of places.  We have to determine if that information is still useful in those places and if so how else to present it.

**Comment by chessbyte** [comment]
@kavyanekkalapu is there UX value to the quadicon in these summary pages?  what do you think?

**Comment by kavyanekkalapu** [comment]
@chessbyte From what i understood on previous discussions with @agrare , by looking at that Quadicon,  we can immediately say provider type and valid status.

**Comment by chessbyte** [comment]
@kavyanekkalapu so, it seems that only 2 parts of the quad-icon are useful (provider type and status), while the other 2 (the boxes with the numbers) are duplicated to the right of it.  Wondering if it would make more sense to expose the Provider Type and Status separately in boxes similar to the other info.

**Comment by agrare** [comment]
Quadicon on the dashboard doesn't make a lost of sense to me since we have all the screen realestate to show whatever we want.

**Comment by agrare** [comment]
I think we did lose some good info when we went to a list view though, there is no iicon or provider auth status on the list view

Screenshot from 2022-03-18 10-24-45

**Comment by chessbyte** [comment]
> I think we did lose some good info when we went to a list view though, there is no iicon or provider auth status on the list view

But those should be easy to add as columns, if needed

**Comment by agrare** [comment]
> But those should be easy to add as columns, if needed

Definitely, not suggesting going back to quadicons just saying we lost some info

**Comment by chessbyte** [comment]
> Quadicon on the dashboard doesn't make a lot of sense to me since we have all the screen realestate to show whatever we want.

@kavyanekkalapu I suggest that we remove the quadicons on the dashboard and add the missing info in a more consistent way with the rest of the screen.  Not urgent - let's just added it to our TODO list

**Comment by Fryguy** [comment]
The old openshift dashsboard just had a big openshift logo where the quadicon is, which looked really nice.  I could see just 2 simple icons side by side for the provider type and the status.

**Review by agrare — APPROVED** [review]

**Pull request merged**
